# 数据库配置
spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:codePan;MODE=MYSQL
    # 初始化数据表 DDL
    schema: classpath:sql/init.sql
    #  初始化数据 DML
    data: classpath:sql/data.sql
    username: root
    password: 12#$asDF
    tomcat:
      test-while-idle: true
      initial-size: 10
      max-active: 30
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        allow: 127.0.0.1
        enabled: true
        login-username: xxcx
        login-password: xxcx
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
      validation-query: select 1
    h2:
      #开启console 访问 默认false
      console:
        enabled: true
        settings:
          # 开启h2 console 跟踪 方便调试  默认 false
          trace: true
          # 允许console 远程访问 默认false
          web-allow-others: true
        # h2 访问路径上下文
        path: /h2-console
# mybatis配置
mybatis:
  type-aliases-package: com.bonc.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml

